#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeNetworkService.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HomeNetwork")]
	public partial class HomeNetworkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsers_HNU(Users_HNU instance);
    partial void UpdateUsers_HNU(Users_HNU instance);
    partial void DeleteUsers_HNU(Users_HNU instance);
    partial void InsertMachines_HNM(Machines_HNM instance);
    partial void UpdateMachines_HNM(Machines_HNM instance);
    partial void DeleteMachines_HNM(Machines_HNM instance);
    partial void InsertNetworkDevices_HNND(NetworkDevices_HNND instance);
    partial void UpdateNetworkDevices_HNND(NetworkDevices_HNND instance);
    partial void DeleteNetworkDevices_HNND(NetworkDevices_HNND instance);
    partial void InsertRouterSetups_HNR(RouterSetups_HNR instance);
    partial void UpdateRouterSetups_HNR(RouterSetups_HNR instance);
    partial void DeleteRouterSetups_HNR(RouterSetups_HNR instance);
    #endregion
		
		public HomeNetworkDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HomeNetworkConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HomeNetworkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HomeNetworkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HomeNetworkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HomeNetworkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vwUser> vwUsers
		{
			get
			{
				return this.GetTable<vwUser>();
			}
		}
		
		public System.Data.Linq.Table<vwNetworkDevice> vwNetworkDevices
		{
			get
			{
				return this.GetTable<vwNetworkDevice>();
			}
		}
		
		public System.Data.Linq.Table<vwMachine> vwMachines
		{
			get
			{
				return this.GetTable<vwMachine>();
			}
		}
		
		public System.Data.Linq.Table<vwRouterName> vwRouterNames
		{
			get
			{
				return this.GetTable<vwRouterName>();
			}
		}
		
		public System.Data.Linq.Table<vwRouterSetup> vwRouterSetups
		{
			get
			{
				return this.GetTable<vwRouterSetup>();
			}
		}
		
		public System.Data.Linq.Table<Users_HNU> Users_HNUs
		{
			get
			{
				return this.GetTable<Users_HNU>();
			}
		}
		
		public System.Data.Linq.Table<Machines_HNM> Machines_HNMs
		{
			get
			{
				return this.GetTable<Machines_HNM>();
			}
		}
		
		public System.Data.Linq.Table<NetworkDevices_HNND> NetworkDevices_HNNDs
		{
			get
			{
				return this.GetTable<NetworkDevices_HNND>();
			}
		}
		
		public System.Data.Linq.Table<RouterSetups_HNR> RouterSetups_HNRs
		{
			get
			{
				return this.GetTable<RouterSetups_HNR>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HNSP_RouterSetup")]
		public ISingleResult<HNSP_RouterSetupResult> HNSP_RouterSetup([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string reqType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string setupID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reqType, setupID);
			return ((ISingleResult<HNSP_RouterSetupResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HNSP_ComboBox")]
		public ISingleResult<HNSP_ComboBoxResult> HNSP_ComboBox([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string reqType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reqType);
			return ((ISingleResult<HNSP_ComboBoxResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HNSP_IP")]
		public ISingleResult<HNSP_IPResult> HNSP_IP()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HNSP_IPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HNSP_IPinfo")]
		public ISingleResult<HNSP_IPinfoResult> HNSP_IPinfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string reqType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string devType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ipAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reqType, devType, ipAddress);
			return ((ISingleResult<HNSP_IPinfoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwUsers")]
	public partial class vwUser
	{
		
		private string _UserID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _MachineName;
		
		private string _Password;
		
		public vwUser()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(100)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(100)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="VarChar(100)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="varchar(max)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwNetworkDevices")]
	public partial class vwNetworkDevice
	{
		
		private string _NetworkDeviceID;
		
		private string _NetworkDeviceName;
		
		private string _MacAddress;
		
		private string _NetworkDeviceType;
		
		private string _Location;
		
		private System.Nullable<int> _NetworkPorts;
		
		private string _IPaddress;
		
		public vwNetworkDevice()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceID", DbType="varchar(50) NOT NULL", CanBeNull=false)]
		public string NetworkDeviceID
		{
			get
			{
				return this._NetworkDeviceID;
			}
			set
			{
				if ((this._NetworkDeviceID != value))
				{
					this._NetworkDeviceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceName", DbType="VarChar(100)")]
		public string NetworkDeviceName
		{
			get
			{
				return this._NetworkDeviceName;
			}
			set
			{
				if ((this._NetworkDeviceName != value))
				{
					this._NetworkDeviceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacAddress", DbType="VarChar(50)")]
		public string MacAddress
		{
			get
			{
				return this._MacAddress;
			}
			set
			{
				if ((this._MacAddress != value))
				{
					this._MacAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceType", DbType="VarChar(50)")]
		public string NetworkDeviceType
		{
			get
			{
				return this._NetworkDeviceType;
			}
			set
			{
				if ((this._NetworkDeviceType != value))
				{
					this._NetworkDeviceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkPorts", DbType="int")]
		public System.Nullable<int> NetworkPorts
		{
			get
			{
				return this._NetworkPorts;
			}
			set
			{
				if ((this._NetworkPorts != value))
				{
					this._NetworkPorts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddress", DbType="varchar(50)")]
		public string IPaddress
		{
			get
			{
				return this._IPaddress;
			}
			set
			{
				if ((this._IPaddress != value))
				{
					this._IPaddress = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwMachines")]
	public partial class vwMachine
	{
		
		private string _MachineID;
		
		private string _MachineName;
		
		private string _MacAddress;
		
		private string _IPaddress;
		
		private System.Nullable<bool> _Static;
		
		private string _MachineType;
		
		private string _NetworkDeviceName;
		
		private string _Location;
		
		private string _HostName;
		
		public vwMachine()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MachineID
		{
			get
			{
				return this._MachineID;
			}
			set
			{
				if ((this._MachineID != value))
				{
					this._MachineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MacAddress
		{
			get
			{
				return this._MacAddress;
			}
			set
			{
				if ((this._MacAddress != value))
				{
					this._MacAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddress", DbType="VarChar(50)")]
		public string IPaddress
		{
			get
			{
				return this._IPaddress;
			}
			set
			{
				if ((this._IPaddress != value))
				{
					this._IPaddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Static", DbType="Bit")]
		public System.Nullable<bool> Static
		{
			get
			{
				return this._Static;
			}
			set
			{
				if ((this._Static != value))
				{
					this._Static = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MachineType
		{
			get
			{
				return this._MachineType;
			}
			set
			{
				if ((this._MachineType != value))
				{
					this._MachineType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceName", DbType="VarChar(100)")]
		public string NetworkDeviceName
		{
			get
			{
				return this._NetworkDeviceName;
			}
			set
			{
				if ((this._NetworkDeviceName != value))
				{
					this._NetworkDeviceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostName", DbType="VarChar(50)")]
		public string HostName
		{
			get
			{
				return this._HostName;
			}
			set
			{
				if ((this._HostName != value))
				{
					this._HostName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwRouterNames")]
	public partial class vwRouterName
	{
		
		private string _Name;
		
		public vwRouterName()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwRouterSetups")]
	public partial class vwRouterSetup
	{
		
		private string _SetupID;
		
		private string _SetupName;
		
		public vwRouterSetup()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SetupID
		{
			get
			{
				return this._SetupID;
			}
			set
			{
				if ((this._SetupID != value))
				{
					this._SetupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupName", DbType="VarChar(100)")]
		public string SetupName
		{
			get
			{
				return this._SetupName;
			}
			set
			{
				if ((this._SetupName != value))
				{
					this._SetupName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users_HNU")]
	public partial class Users_HNU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Password;
		
		private string _MachineID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnMachineIDChanging(string value);
    partial void OnMachineIDChanged();
    #endregion
		
		public Users_HNU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(100)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(100)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineID", DbType="VarChar(50)")]
		public string MachineID
		{
			get
			{
				return this._MachineID;
			}
			set
			{
				if ((this._MachineID != value))
				{
					this.OnMachineIDChanging(value);
					this.SendPropertyChanging();
					this._MachineID = value;
					this.SendPropertyChanged("MachineID");
					this.OnMachineIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Machines_HNM")]
	public partial class Machines_HNM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MachineID;
		
		private string _MachineName;
		
		private string _MacAddress;
		
		private string _IPaddress;
		
		private System.Nullable<bool> _Static;
		
		private int _MachineTypeID;
		
		private string _NetworkDeviceID;
		
		private System.Nullable<int> _LocationID;
		
		private string _HostName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMachineIDChanging(string value);
    partial void OnMachineIDChanged();
    partial void OnMachineNameChanging(string value);
    partial void OnMachineNameChanged();
    partial void OnMacAddressChanging(string value);
    partial void OnMacAddressChanged();
    partial void OnIPaddressChanging(string value);
    partial void OnIPaddressChanged();
    partial void OnStaticChanging(System.Nullable<bool> value);
    partial void OnStaticChanged();
    partial void OnMachineTypeIDChanging(int value);
    partial void OnMachineTypeIDChanged();
    partial void OnNetworkDeviceIDChanging(string value);
    partial void OnNetworkDeviceIDChanged();
    partial void OnLocationIDChanging(System.Nullable<int> value);
    partial void OnLocationIDChanged();
    partial void OnHostNameChanging(string value);
    partial void OnHostNameChanged();
    #endregion
		
		public Machines_HNM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MachineID
		{
			get
			{
				return this._MachineID;
			}
			set
			{
				if ((this._MachineID != value))
				{
					this.OnMachineIDChanging(value);
					this.SendPropertyChanging();
					this._MachineID = value;
					this.SendPropertyChanged("MachineID");
					this.OnMachineIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this.OnMachineNameChanging(value);
					this.SendPropertyChanging();
					this._MachineName = value;
					this.SendPropertyChanged("MachineName");
					this.OnMachineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MacAddress
		{
			get
			{
				return this._MacAddress;
			}
			set
			{
				if ((this._MacAddress != value))
				{
					this.OnMacAddressChanging(value);
					this.SendPropertyChanging();
					this._MacAddress = value;
					this.SendPropertyChanged("MacAddress");
					this.OnMacAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddress", DbType="VarChar(50)")]
		public string IPaddress
		{
			get
			{
				return this._IPaddress;
			}
			set
			{
				if ((this._IPaddress != value))
				{
					this.OnIPaddressChanging(value);
					this.SendPropertyChanging();
					this._IPaddress = value;
					this.SendPropertyChanged("IPaddress");
					this.OnIPaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Static", DbType="Bit")]
		public System.Nullable<bool> Static
		{
			get
			{
				return this._Static;
			}
			set
			{
				if ((this._Static != value))
				{
					this.OnStaticChanging(value);
					this.SendPropertyChanging();
					this._Static = value;
					this.SendPropertyChanged("Static");
					this.OnStaticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineTypeID", DbType="Int NOT NULL")]
		public int MachineTypeID
		{
			get
			{
				return this._MachineTypeID;
			}
			set
			{
				if ((this._MachineTypeID != value))
				{
					this.OnMachineTypeIDChanging(value);
					this.SendPropertyChanging();
					this._MachineTypeID = value;
					this.SendPropertyChanged("MachineTypeID");
					this.OnMachineTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceID", DbType="VarChar(50)")]
		public string NetworkDeviceID
		{
			get
			{
				return this._NetworkDeviceID;
			}
			set
			{
				if ((this._NetworkDeviceID != value))
				{
					this.OnNetworkDeviceIDChanging(value);
					this.SendPropertyChanging();
					this._NetworkDeviceID = value;
					this.SendPropertyChanged("NetworkDeviceID");
					this.OnNetworkDeviceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int")]
		public System.Nullable<int> LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this.OnLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LocationID = value;
					this.SendPropertyChanged("LocationID");
					this.OnLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostName", DbType="VarChar(50)")]
		public string HostName
		{
			get
			{
				return this._HostName;
			}
			set
			{
				if ((this._HostName != value))
				{
					this.OnHostNameChanging(value);
					this.SendPropertyChanging();
					this._HostName = value;
					this.SendPropertyChanged("HostName");
					this.OnHostNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NetworkDevices_HNND")]
	public partial class NetworkDevices_HNND : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NetworkDeviceID;
		
		private string _NetworkDeviceName;
		
		private string _MacAddress;
		
		private string _IPaddress;
		
		private System.Nullable<int> _NetworkDeviceTypeID;
		
		private System.Nullable<int> _NetworkPorts;
		
		private System.Nullable<int> _LocationID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNetworkDeviceIDChanging(string value);
    partial void OnNetworkDeviceIDChanged();
    partial void OnNetworkDeviceNameChanging(string value);
    partial void OnNetworkDeviceNameChanged();
    partial void OnMacAddressChanging(string value);
    partial void OnMacAddressChanged();
    partial void OnIPaddressChanging(string value);
    partial void OnIPaddressChanged();
    partial void OnNetworkDeviceTypeIDChanging(System.Nullable<int> value);
    partial void OnNetworkDeviceTypeIDChanged();
    partial void OnNetworkPortsChanging(System.Nullable<int> value);
    partial void OnNetworkPortsChanged();
    partial void OnLocationIDChanging(System.Nullable<int> value);
    partial void OnLocationIDChanged();
    #endregion
		
		public NetworkDevices_HNND()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NetworkDeviceID
		{
			get
			{
				return this._NetworkDeviceID;
			}
			set
			{
				if ((this._NetworkDeviceID != value))
				{
					this.OnNetworkDeviceIDChanging(value);
					this.SendPropertyChanging();
					this._NetworkDeviceID = value;
					this.SendPropertyChanged("NetworkDeviceID");
					this.OnNetworkDeviceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceName", DbType="VarChar(100)")]
		public string NetworkDeviceName
		{
			get
			{
				return this._NetworkDeviceName;
			}
			set
			{
				if ((this._NetworkDeviceName != value))
				{
					this.OnNetworkDeviceNameChanging(value);
					this.SendPropertyChanging();
					this._NetworkDeviceName = value;
					this.SendPropertyChanged("NetworkDeviceName");
					this.OnNetworkDeviceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacAddress", DbType="VarChar(50)")]
		public string MacAddress
		{
			get
			{
				return this._MacAddress;
			}
			set
			{
				if ((this._MacAddress != value))
				{
					this.OnMacAddressChanging(value);
					this.SendPropertyChanging();
					this._MacAddress = value;
					this.SendPropertyChanged("MacAddress");
					this.OnMacAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddress", DbType="varchar(50)")]
		public string IPaddress
		{
			get
			{
				return this._IPaddress;
			}
			set
			{
				if ((this._IPaddress != value))
				{
					this.OnIPaddressChanging(value);
					this.SendPropertyChanging();
					this._IPaddress = value;
					this.SendPropertyChanged("IPaddress");
					this.OnIPaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceTypeID", DbType="Int")]
		public System.Nullable<int> NetworkDeviceTypeID
		{
			get
			{
				return this._NetworkDeviceTypeID;
			}
			set
			{
				if ((this._NetworkDeviceTypeID != value))
				{
					this.OnNetworkDeviceTypeIDChanging(value);
					this.SendPropertyChanging();
					this._NetworkDeviceTypeID = value;
					this.SendPropertyChanged("NetworkDeviceTypeID");
					this.OnNetworkDeviceTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkPorts", DbType="Int")]
		public System.Nullable<int> NetworkPorts
		{
			get
			{
				return this._NetworkPorts;
			}
			set
			{
				if ((this._NetworkPorts != value))
				{
					this.OnNetworkPortsChanging(value);
					this.SendPropertyChanging();
					this._NetworkPorts = value;
					this.SendPropertyChanged("NetworkPorts");
					this.OnNetworkPortsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int")]
		public System.Nullable<int> LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this.OnLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LocationID = value;
					this.SendPropertyChanged("LocationID");
					this.OnLocationIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RouterSetups_HNRS")]
	public partial class RouterSetups_HNR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SetupID;
		
		private string _SetupName;
		
		private string _Name;
		
		private string _IPaddress;
		
		private string _UserID;
		
		private string _Password;
		
		private string _SSID24;
		
		private string _Password24;
		
		private string _SSID50;
		
		private string _Password50;
		
		private string _EncryptionType;
		
		private string _Mode;
		
		private string _Comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSetupIDChanging(string value);
    partial void OnSetupIDChanged();
    partial void OnSetupNameChanging(string value);
    partial void OnSetupNameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIPaddressChanging(string value);
    partial void OnIPaddressChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSSID24Changing(string value);
    partial void OnSSID24Changed();
    partial void OnPassword24Changing(string value);
    partial void OnPassword24Changed();
    partial void OnSSID50Changing(string value);
    partial void OnSSID50Changed();
    partial void OnPassword50Changing(string value);
    partial void OnPassword50Changed();
    partial void OnEncryptionTypeChanging(string value);
    partial void OnEncryptionTypeChanged();
    partial void OnModeChanging(string value);
    partial void OnModeChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    #endregion
		
		public RouterSetups_HNR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SetupID
		{
			get
			{
				return this._SetupID;
			}
			set
			{
				if ((this._SetupID != value))
				{
					this.OnSetupIDChanging(value);
					this.SendPropertyChanging();
					this._SetupID = value;
					this.SendPropertyChanged("SetupID");
					this.OnSetupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupName", DbType="VarChar(100)")]
		public string SetupName
		{
			get
			{
				return this._SetupName;
			}
			set
			{
				if ((this._SetupName != value))
				{
					this.OnSetupNameChanging(value);
					this.SendPropertyChanging();
					this._SetupName = value;
					this.SendPropertyChanged("SetupName");
					this.OnSetupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddress", DbType="VarChar(50)")]
		public string IPaddress
		{
			get
			{
				return this._IPaddress;
			}
			set
			{
				if ((this._IPaddress != value))
				{
					this.OnIPaddressChanging(value);
					this.SendPropertyChanging();
					this._IPaddress = value;
					this.SendPropertyChanged("IPaddress");
					this.OnIPaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSID24", DbType="VarChar(50)")]
		public string SSID24
		{
			get
			{
				return this._SSID24;
			}
			set
			{
				if ((this._SSID24 != value))
				{
					this.OnSSID24Changing(value);
					this.SendPropertyChanging();
					this._SSID24 = value;
					this.SendPropertyChanged("SSID24");
					this.OnSSID24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password24", DbType="VarChar(MAX)")]
		public string Password24
		{
			get
			{
				return this._Password24;
			}
			set
			{
				if ((this._Password24 != value))
				{
					this.OnPassword24Changing(value);
					this.SendPropertyChanging();
					this._Password24 = value;
					this.SendPropertyChanged("Password24");
					this.OnPassword24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSID50", DbType="VarChar(50)")]
		public string SSID50
		{
			get
			{
				return this._SSID50;
			}
			set
			{
				if ((this._SSID50 != value))
				{
					this.OnSSID50Changing(value);
					this.SendPropertyChanging();
					this._SSID50 = value;
					this.SendPropertyChanged("SSID50");
					this.OnSSID50Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password50", DbType="VarChar(MAX)")]
		public string Password50
		{
			get
			{
				return this._Password50;
			}
			set
			{
				if ((this._Password50 != value))
				{
					this.OnPassword50Changing(value);
					this.SendPropertyChanging();
					this._Password50 = value;
					this.SendPropertyChanged("Password50");
					this.OnPassword50Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncryptionType", DbType="VarChar(50)")]
		public string EncryptionType
		{
			get
			{
				return this._EncryptionType;
			}
			set
			{
				if ((this._EncryptionType != value))
				{
					this.OnEncryptionTypeChanging(value);
					this.SendPropertyChanging();
					this._EncryptionType = value;
					this.SendPropertyChanged("EncryptionType");
					this.OnEncryptionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mode", DbType="VarChar(50)")]
		public string Mode
		{
			get
			{
				return this._Mode;
			}
			set
			{
				if ((this._Mode != value))
				{
					this.OnModeChanging(value);
					this.SendPropertyChanging();
					this._Mode = value;
					this.SendPropertyChanged("Mode");
					this.OnModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(MAX)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class HNSP_RouterSetupResult
	{
		
		private string _SetupID;
		
		private string _SetupName;
		
		private string _Name;
		
		private string _IPaddress;
		
		private string _UserID;
		
		private string _Password;
		
		private string _SSID24;
		
		private string _Password24;
		
		private string _SSID50;
		
		private string _Password50;
		
		private string _EncryptionType;
		
		private string _Mode;
		
		private string _Comments;
		
		public HNSP_RouterSetupResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SetupID
		{
			get
			{
				return this._SetupID;
			}
			set
			{
				if ((this._SetupID != value))
				{
					this._SetupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetupName", DbType="VarChar(100)")]
		public string SetupName
		{
			get
			{
				return this._SetupName;
			}
			set
			{
				if ((this._SetupName != value))
				{
					this._SetupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddress", DbType="VarChar(50)")]
		public string IPaddress
		{
			get
			{
				return this._IPaddress;
			}
			set
			{
				if ((this._IPaddress != value))
				{
					this._IPaddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(50)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSID24", DbType="VarChar(50)")]
		public string SSID24
		{
			get
			{
				return this._SSID24;
			}
			set
			{
				if ((this._SSID24 != value))
				{
					this._SSID24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password24", DbType="VarChar(MAX)")]
		public string Password24
		{
			get
			{
				return this._Password24;
			}
			set
			{
				if ((this._Password24 != value))
				{
					this._Password24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSID50", DbType="VarChar(50)")]
		public string SSID50
		{
			get
			{
				return this._SSID50;
			}
			set
			{
				if ((this._SSID50 != value))
				{
					this._SSID50 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password50", DbType="VarChar(MAX)")]
		public string Password50
		{
			get
			{
				return this._Password50;
			}
			set
			{
				if ((this._Password50 != value))
				{
					this._Password50 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncryptionType", DbType="VarChar(50)")]
		public string EncryptionType
		{
			get
			{
				return this._EncryptionType;
			}
			set
			{
				if ((this._EncryptionType != value))
				{
					this._EncryptionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mode", DbType="VarChar(50)")]
		public string Mode
		{
			get
			{
				return this._Mode;
			}
			set
			{
				if ((this._Mode != value))
				{
					this._Mode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(MAX)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this._Comments = value;
				}
			}
		}
	}
	
	public partial class HNSP_ComboBoxResult
	{
		
		private string _cboMember;
		
		private string _cboDisplay;
		
		public HNSP_ComboBoxResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cboMember", DbType="VarChar(50)")]
		public string cboMember
		{
			get
			{
				return this._cboMember;
			}
			set
			{
				if ((this._cboMember != value))
				{
					this._cboMember = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cboDisplay", DbType="VarChar(50)")]
		public string cboDisplay
		{
			get
			{
				return this._cboDisplay;
			}
			set
			{
				if ((this._cboDisplay != value))
				{
					this._cboDisplay = value;
				}
			}
		}
	}
	
	public partial class HNSP_IPResult
	{
		
		private string _IPaddress;
		
		private string _DeviceName;
		
		private string _HostName;
		
		private string _MacAddress;
		
		private string _NetworkDevice;
		
		private string _devType;
		
		public HNSP_IPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddress", DbType="VarChar(50)")]
		public string IPaddress
		{
			get
			{
				return this._IPaddress;
			}
			set
			{
				if ((this._IPaddress != value))
				{
					this._IPaddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceName", DbType="VarChar(100)")]
		public string DeviceName
		{
			get
			{
				return this._DeviceName;
			}
			set
			{
				if ((this._DeviceName != value))
				{
					this._DeviceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostName", DbType="VarChar(100)")]
		public string HostName
		{
			get
			{
				return this._HostName;
			}
			set
			{
				if ((this._HostName != value))
				{
					this._HostName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacAddress", DbType="VarChar(50)")]
		public string MacAddress
		{
			get
			{
				return this._MacAddress;
			}
			set
			{
				if ((this._MacAddress != value))
				{
					this._MacAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDevice", DbType="VarChar(100)")]
		public string NetworkDevice
		{
			get
			{
				return this._NetworkDevice;
			}
			set
			{
				if ((this._NetworkDevice != value))
				{
					this._NetworkDevice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string devType
		{
			get
			{
				return this._devType;
			}
			set
			{
				if ((this._devType != value))
				{
					this._devType = value;
				}
			}
		}
	}
	
	public partial class HNSP_IPinfoResult
	{
		
		private string _IPaddressM;
		
		private string _MachineName;
		
		private string _HostName;
		
		private System.Nullable<bool> _Static;
		
		private string _MachineType;
		
		private string _NetworkDeviceName;
		
		private string _LocationM;
		
		private string _IPaddressN;
		
		private string _MacAddress;
		
		private System.Nullable<int> _NetworkPorts;
		
		private string _NetworkDeviceType;
		
		private string _LocationN;
		
		public HNSP_IPinfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddressM", DbType="VarChar(50)")]
		public string IPaddressM
		{
			get
			{
				return this._IPaddressM;
			}
			set
			{
				if ((this._IPaddressM != value))
				{
					this._IPaddressM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostName", DbType="VarChar(50)")]
		public string HostName
		{
			get
			{
				return this._HostName;
			}
			set
			{
				if ((this._HostName != value))
				{
					this._HostName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Static", DbType="Bit")]
		public System.Nullable<bool> Static
		{
			get
			{
				return this._Static;
			}
			set
			{
				if ((this._Static != value))
				{
					this._Static = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MachineType
		{
			get
			{
				return this._MachineType;
			}
			set
			{
				if ((this._MachineType != value))
				{
					this._MachineType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceName", DbType="VarChar(100)")]
		public string NetworkDeviceName
		{
			get
			{
				return this._NetworkDeviceName;
			}
			set
			{
				if ((this._NetworkDeviceName != value))
				{
					this._NetworkDeviceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationM", DbType="VarChar(50)")]
		public string LocationM
		{
			get
			{
				return this._LocationM;
			}
			set
			{
				if ((this._LocationM != value))
				{
					this._LocationM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPaddressN", DbType="VarChar(50)")]
		public string IPaddressN
		{
			get
			{
				return this._IPaddressN;
			}
			set
			{
				if ((this._IPaddressN != value))
				{
					this._IPaddressN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MacAddress", DbType="VarChar(50)")]
		public string MacAddress
		{
			get
			{
				return this._MacAddress;
			}
			set
			{
				if ((this._MacAddress != value))
				{
					this._MacAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkPorts", DbType="Int")]
		public System.Nullable<int> NetworkPorts
		{
			get
			{
				return this._NetworkPorts;
			}
			set
			{
				if ((this._NetworkPorts != value))
				{
					this._NetworkPorts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkDeviceType", DbType="VarChar(50)")]
		public string NetworkDeviceType
		{
			get
			{
				return this._NetworkDeviceType;
			}
			set
			{
				if ((this._NetworkDeviceType != value))
				{
					this._NetworkDeviceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationN", DbType="VarChar(50)")]
		public string LocationN
		{
			get
			{
				return this._LocationN;
			}
			set
			{
				if ((this._LocationN != value))
				{
					this._LocationN = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
